### ISSUE TITLE
Definitions 'ref' is injected, not referenced

### ISSUE THREAD

**Issue by NadavK** [mohsen1/multi-file-swagger-example#1]
In your example, foo.yaml contains a reference to the user definition:

```
ref: '#/definitions/User'
```

but this gets resolved to the actual object definition

<pre>
swagger: '2.0'
  /bar:
    get:
      responses:
        '200':
          description: OK
          schema:
<b>            type: object
            properties:
              name:
                type: string</b>
definitions:
  User:
    type: object
    properties:
      name:
        type: string
</pre>

instead of just including the ref as I would expect (is my expectation erroneous?)

<pre>
swagger: '2.0'
  /bar:
    get:
      responses:
        '200':
          description: OK
          schema:
            <b>$ref: '#/definitions/User'</b>
definitions:
  User:
    type: object
    properties:
      name:
        type: string
</pre>

**Comment by mohsen1** [comment]
It's a limitation of json-refs. Please follow https://github.com/whitlockjc/json-refs/issues/27

**Comment by dylan-colaco** [comment]
Can this be done now?

**Comment by dylan-colaco** [comment]
It looks like json-refs can do it: https://github.com/whitlockjc/json-refs/issues/125

**Comment by ClaudioConsolmagno** [comment]
Reviving this somewhat old thread. What would it take to update the lib to the latest json-refs version? I could create a pull request to just update the version but is that going to be accepted?

**Comment by ClaudioConsolmagno** [comment]
@mohsen1 Took me a while but I finally created that PR (https://github.com/mohsen1/multi-file-swagger-example/pull/21). Didn't want to simply update the versions in case it broke other functionality so also added a lightweight regression test as well.
