### ISSUE TITLE
Where to put resolve.js in swagger generated structure

### ISSUE THREAD

**Issue by sandip8600** [mohsen1/multi-file-swagger-example#10]

**Comment by mohsen1** [comment]
I'm not following exacly. Can you give more details?

**Comment by dmk255** [comment]
I believe the question is in regards to running a command like 'swagger project <project name>' which generates a sample swagger project using swagger-express-mw.

see https://scotch.io/tutorials/speed-up-your-restful-api-development-in-node-js-with-swagger for an example. I'm also curious about the answer to this question.
