### ISSUE TITLE
Cannot create property on string

### ISSUE THREAD

**Issue by falico** [mohsen1/multi-file-swagger-example#11]
Hi,

I tried this approach of splitting everything, including "paths" and "definitions", but these two last steps didn't work. I don't know if I am missing something, but the library is handling the "$ref" attribute as string, and it fails. Here is what I am getting for "definitions" if I try to set it as a ref:

Cannot create property 'id' on string 'definitions/index.json'

Have you also faced this error before?

**Comment by mohsen1** [comment]
JSON Refs has changed since this was created. Use the version I was using here. Look at package.json.

**Comment by falico** [comment]
thanks @mohsen1 ! Nice call :)
